language: node_js
sudo: false
node_js:
- stable
- 6
- 5
- 4
notifications:
  email: false
  slack:
    secure: UOrMogUpGMmIq5yB7OudUav7IHizCV0gkvMVAveAxF8U7tkC6WmkWS5mmNOQfesjmvPkIO7hMd3eM2xPfiumbb8R8sRzJNpVcIdN/33Rjr1Jle8Oj0hjbqmoI+uvBuGQ1htxQPTzF0RbyMjoHZ+xAe4Fwh1lsefE5l+LXPPVGz7oCykSEX+R+vda7D1wBFmcJtAwdORzrAHv7rSToatUx64dBmclQ0replnpCILLgtfjCxDfgSC+uw+6MqpVBdVWWNvLw60BzUMcWAGR8lhGYE8Fb1TC1kC8ODb12lgP3hobjQnUb5lgb3ZAZOmZ9XTSWKOkwi5sxArEoC+kpZeqJjPCcABYlNyYHEf5o4g6Ug33AfjqGLw4R+Iv4SVKY6v4Q83SeJibYKYOjBl82sjesJeizOdbhgHaozI2fjPBXNy5ujQ0eydtEbX6bBRwIkr08UA2Fopz+14lGD21rkS3wrqAOzb4PTf8WvqcIn4JUszJxix4W1DdY/q79ewMJUfIwDbrtR6nFP/tCCzBousZChZwIK0IwO1WA9WPtOPdCBY0lRhaWlWMA+7NWif5wZWUl8ZgpSDrKSCuXLdc18/xub5FGqDa64VwrSeHm3Vhu6UYbzvG472boMIZ2F7teiokvrrIiOMhocTsxwQXaxXCfgap4Ibxa2pB4Vx6VhiN72Y=
