language: node_js
sudo: false
node_js: stable
cache:
  yarn: true
  directories:
  - node_modules
env:
  matrix:
  - CI_MODE=sauce
  - CI_MODE=karma
  - CI_MODE=jsdom
matrix:
  fast_finish: true
  allow_failures:
  - env: CI_MODE=sauce
script:
- npm run ci:$CI_MODE
after_success:
- npm run coverage:$CI_MODE
notifications:
  slack:
    secure: U3uzO3B/0Ri3MeHJANkJwMNzEw6hrErULn26VPQvyQJ0k0FwjziUt9/rNy2dl1U1Nn378zz27aA+r3IA7MmxNZL09QoJuvwbRkXFm+GlQoN53dJkH/q3M/Hvak1A+ET2f537Ak9IfOGJa++aEPr6Pk0MC/abts0tDv1YVCic9uZMsJV8fBQX338lvHKJStwuHHCjlz3HmwoJZtilgpwtHlPl1UwAL6h3885Qm+mZ9pt6PGSy619ac39gF3dVKtw459wctwvlM5GJq8A+ixMlUrQhOnNtKuccKcUkyjxTFZ7iLPM3OODF4UYzoLm6+m/6wN1SlxPM+zinq1ugb+5b41axpWJrBAyj1KUIKzxJRbE0tIGfAVHopkJifwmuU+ypbHFQnxCg49+VSUyNrasuRIhwmIiRq0weYELgDVtu4O1hwp4UHokpd5OJ4eSdKWAt8qScaFBqZSgWkm8uMa6N2qQWfVA4uHaTS67uYfghxhbAtbR1IhsBwCbKiG2hl9MxZ0BFa+9/1NWIC61LnEtB7lo6fO4K2TpqR7lZ75+/RELROBAehdoI5iQqbUxe40PFePKDr8fCXDUaTs6al+35l+pYLPFz2dI8ave8TSlSYK4RFfdpZlM/Db4mHcI8FGc5woI+hc6u5jvT5cj71abMAqQ+Lwl4NcfjjJkAWq63PYU=
before_deploy:
- npm run build
deploy:
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAJGRQLUF4DJQRRPGA
  secret_access_key:
    secure: aTQLdKpTJORmb60PYD20AAp8D7hc6J9slNHewuqUcfIWO7KVq7PQovvJ0gRaBIcz3uPd0SZ5u8/sfrO4YXH4ChiFje/Qgwsgci6nqEwKtIULCqTNREkkTPqKKssYYq/6d3a35+9oXHsRroUa2qybX4YJHk6IXmY7QhQryn2RIN6eXpCX9pGnji7Ql30cq9QaH3sstE4pvjZux71+U6ee7OZtRJxZ13TvGQLGdhziQog10/8QVlRKgwQzYSIu5Ikga01I+ToMlkjJVGqku4KDCvXIdz7IL9KvUYIGgNGPeDIBy2rVNeP95UhYcPu9W41CM5zMVT0aO0n7CdfJ7/zoWkiI4O3uxOkmLk9noVzApClSVsYWTTz7uGJumPgM/URYlboxLoSA6PcSwvtQhrJ0RZTNtFpYPfreSveQhaQFF8F80S9C1ZSPBInMJB386Hp6/9a9ZZ9pbwK+zzKVAX2lNv+F7bavi1nBFd1vrW/tfMqJfMoiynZqZWAjPQdvNnMRO2cXM8vvJg9IOixRaOcU9UE/bDL2/6gOZ5BjrDcecOuLfTwp9M0F8ISUEBlZrFvecaYHKXZYoT8vHxW4APo7BCXCts/hcS2JzN3IL/U2hDtW5D030kphtTrzUmOs7J3SxMevl8m5yMjAjY2ma8Wz/y6ZHhEQ38o3atv0nwPsrzk=
  bucket: s3-bucket-cdn-s3bucket-1rr97tspu1fmp
  local-dir: lib/build
  upload-dir: "agent/$TRAVIS_BRANCH"
  on:
    tags: true
    repo: userdive/agent.js
    all_branches: true
