language: node_js
sudo: false
node_js:
- stable
- 6
env:
  matrix:
  - BROWSER=sp
  - BROWSER=jsdom
script:
- npm run ci:$BROWSER
after_success:
- ls coverage
- npm run coverage:$BROWSER
notifications:
  email: false
