language: node_js
sudo: false
node_js: stable
env:
  matrix:
  - CI_MODE=sauce
  - CI_MODE=karma
  - CI_MODE=jsdom
matrix:
  fast_finish: true
  allow_failures:
    - env: "CI_MODE=sauce"
script:
- npm run ci:$BROWSER
after_success:
- npm run coverage:$BROWSER
notifications:
  email: false
